class WorkoutsList {
// Class responsible for showing workouts (To-do : turn it into API)
  static List allWorkoutsList = [
    {
      "workOutTitle": "Yoga exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "12",
      "movesNumber": "25",
      "setsNumber": "10",
      "durationInMinutes": "44",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "12,00",
      "hasFreeTrial": "false",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Example exercises",
      "imagePath": "imgs/jiabcyzut.png",
      "timeLeftInHour": "1",
      "movesNumber": "08",
      "setsNumber": "22",
      "durationInMinutes": "15",
      "rating": "2",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "3,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "Example exercises",
      "imagePath": "imgs/welcomeOverlayImg.png",
      "timeLeftInHour": "40",
      "movesNumber": "10",
      "setsNumber": "10",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Yoga exerciiiiiiiiiiiises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "12",
      "movesNumber": "25",
      "setsNumber": "10",
      "durationInMinutes": "44",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "12,00",
      "hasFreeTrial": "false",
    },
    {
      "workOutTitle": "Yoga exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "12",
      "movesNumber": "25",
      "setsNumber": "10",
      "durationInMinutes": "44",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "12,00",
      "hasFreeTrial": "false",
    },
    {
      "workOutTitle": "Example exercises",
      "imagePath": "imgs/jiabcyzut.png",
      "timeLeftInHour": "1",
      "movesNumber": "08",
      "setsNumber": "22",
      "durationInMinutes": "15",
      "rating": "2",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "3,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Example exercises",
      "imagePath": "imgs/welcomeOverlayImg.png",
      "timeLeftInHour": "40",
      "movesNumber": "10",
      "setsNumber": "10",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Yoga exerciiiiiiiiiiiises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "12",
      "movesNumber": "25",
      "setsNumber": "10",
      "durationInMinutes": "44",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "12,00",
      "hasFreeTrial": "false",
      "dailyFreeWorkout": "true",
    },
  ];

  static List hardWorkoutsList = [
    {
      "workOutTitle": "Hard exercises",
      "imagePath": "imgs/loginOverlayImg.png",
      "timeLeftInHour": "11",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "15,00",
      "hasFreeTrial": "false",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "hard muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "9",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "1",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "random hard exercises",
      "imagePath": "imgs/welcomePageOverlay.png",
      "timeLeftInHour": "11",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "2",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Hard exercises",
      "imagePath": "imgs/loginOverlayImg.png",
      "timeLeftInHour": "11",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "15,00",
      "hasFreeTrial": "false",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "hard muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "9",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "1",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "random hard exercises",
      "imagePath": "imgs/welcomePageOverlay.png",
      "timeLeftInHour": "11",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "2",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
  ];

  static List easyWorkoutsList = [
    {
      "workOutTitle": "Easy exercises",
      "imagePath": "imgs/loginOverlayImg.png",
      "timeLeftInHour": "11",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "1. ABC\n\n2.DEF\n\n3.GHI\n\n4.JKL",
      "reviews": "review#1\n\nreview#2\n\nreview#3",
      "comments": "comment#1\n\ncomment#2\n\ncomment#3",
      "priceInDollars": "15,00",
      "hasFreeTrial": "false",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Easy muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "9",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "1",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "random Easy exercises",
      "imagePath": "imgs/welcomePageOverlay.png",
      "timeLeftInHour": "11",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "2",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Easy exercises",
      "imagePath": "imgs/loginOverlayImg.png",
      "timeLeftInHour": "11",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "15,00",
      "hasFreeTrial": "false",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Easy muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "9",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "1",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "random Easy exercises",
      "imagePath": "imgs/welcomePageOverlay.png",
      "timeLeftInHour": "11",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "2",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
  ];

  static List popularWorkoutsList = [
    {
      "workOutTitle": "Hard exercises",
      "imagePath": "imgs/loginOverlayImg.png",
      "timeLeftInHour": "10",
      "movesNumber": "40",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "5",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "hard muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "22",
      "movesNumber": "40",
      "setsNumber": "20",
      "durationInMinutes": "30",
      "rating": "5",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "30,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "random hard exercises",
      "imagePath": "imgs/welcomePageOverlay.png",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Hard exercises",
      "imagePath": "imgs/loginOverlayImg.png",
      "timeLeftInHour": "10",
      "movesNumber": "40",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "5",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "hard muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "22",
      "movesNumber": "40",
      "setsNumber": "20",
      "durationInMinutes": "30",
      "rating": "5",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "30,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "random hard exercises",
      "imagePath": "imgs/welcomePageOverlay.png",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
  ];

  static List mediumWorkoutsList = [
    {
      "workOutTitle": "Hard exercises",
      "imagePath": "imgs/loginOverlayImg.png",
      "timeLeftInHour": "19",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "hard muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "18",
      "movesNumber": "24",
      "setsNumber": "12",
      "durationInMinutes": "20",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "8,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "random hard exercises",
      "imagePath": "imgs/welcomePageOverlay.png",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Hard exercises",
      "imagePath": "imgs/loginOverlayImg.png",
      "timeLeftInHour": "19",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "hard muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "18",
      "movesNumber": "24",
      "setsNumber": "12",
      "durationInMinutes": "20",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "8,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "random hard exercises",
      "imagePath": "imgs/welcomePageOverlay.png",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
  ];
}
